### ISSUE TITLE
incorrect keyboard mappings for jinlon

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/eupnea-utils#11]
Here is what jinlon's keyboard looks like (it has 14 keys to the right of ESC): 
![PXL_20230512_234958634](https://github.com/eupnea-linux/eupnea-utils/assets/52586855/6d868a3e-74b2-42f4-a633-0e1087220a86)

**Comment by ChocolateLoverRaj** [comment]
I can probably make a PR for this

**Comment by ChocolateLoverRaj** [comment]
I figuired out the issue: Both the Brightness up key and the Keyboard brightness down keys are shown as "brightness up" keys. 

`sudo evtest` shows that The brightness up key is code `95` and the keyboard brightness down key is code `97`. 

The problem is that I don't think there is a way in keyd config to specifically target key with code `97`. I think something other than `keyd` (maybe in addition to `keyd`) needs to be used to fix this.

**Comment by ChocolateLoverRaj** [comment]
This is the output of `evtest` after pressing the brightness up key and then the keyboard brightness down key:
```
Event: time 1684030040.514007, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1c
Event: time 1684030040.514007, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1684030040.514007, -------------- SYN_REPORT ------------
Event: time 1684030047.580685, type 4 (EV_MSC), code 4 (MSC_SCAN), value 95
Event: time 1684030047.580685, type 1 (EV_KEY), code 225 (KEY_BRIGHTNESSUP), value 1
Event: time 1684030047.580685, -------------- SYN_REPORT ------------
Event: time 1684030047.643182, type 4 (EV_MSC), code 4 (MSC_SCAN), value 95
Event: time 1684030047.643182, type 1 (EV_KEY), code 225 (KEY_BRIGHTNESSUP), value 0
Event: time 1684030047.643182, -------------- SYN_REPORT ------------
Event: time 1684030050.307931, type 4 (EV_MSC), code 4 (MSC_SCAN), value 97
Event: time 1684030050.307931, type 1 (EV_KEY), code 225 (KEY_BRIGHTNESSUP), value 1
Event: time 1684030050.307931, -------------- SYN_REPORT ------------
Event: time 1684030050.359049, type 4 (EV_MSC), code 4 (MSC_SCAN), value 97
Event: time 1684030050.359049, type 1 (EV_KEY), code 225 (KEY_BRIGHTNESSUP), value 0
Event: time 1684030050.359049, -------------- SYN_REPORT ------------
```

**Comment by Apacelus** [comment]
Im gonna assume jinlon uses vivaldi.

This 848a430cc2149b5635787f00a13bdf08105e2466 should fix the jinlon layout

**Comment by ChocolateLoverRaj** [comment]
I ran that command and I got this output:
```
Setting keyboard layout to: cros-standard.conf
```
I restarted `keyd`. The 2 keys still don't work.

**Comment by ChocolateLoverRaj** [comment]
Here is how I fixed it manually, by following this guide https://wiki.archlinux.org/title/map_scancodes_to_keycodes#2.1:
- I created a file named `/etc/udev/hwdb.d/90-custom-keyboard.hwdb` (needs sudo)
- This is the contents of the file:
```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svn*:pn*:pvr*
 KEYBOARD_KEY_97=!kbdillumdown
```
- I ran `sudo systemd-hwdb update`
- I ran `sudo udevadm trigger`
- I enabled `keyd` (I'm not sure if keyd needs to be restarted if it's already started, but it was stopped for me when I started it)

**Comment by ChocolateLoverRaj** [comment]
Please add me as a [commit co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) to the commit adding these fixes (my email is `52586855+ChocolateLoverRaj@users.noreply.github.com`). You can just add
```
Co-authored-by: Rajas Paranjpe <52586855+ChocolateLoverRaj@users.noreply.github.com>
```

**Comment by ChocolateLoverRaj** [comment]
I created a repo with a script to automatically fix this: https://github.com/ChocolateLoverRaj/jinlon-scan-code-fix
